name: SPF Websites
favicon: null
layout_spectrum: 0.35841934755444527
typography_spectrum: 0.29356424743309617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.39203824615105987
  lightness: 0.6242726505734026
  saturation: 0.35076719406060874
  rhythmicContrast: 0.49796527344733477
purpose: []
